### ISSUE TITLE
how do I revert to an older version of flagrum

### ISSUE THREAD

**Issue by canplx** [Kizari/Flagrum#111]
just to need to know if I can go back to and older version of flagrum

**Comment by Kizari** [comment]
It's not possible. The old releases are taken down when new ones are released as reverting to old versions can cause huge data corruption of the mods and profiles due to changes to the way Flagrum works internally. It is also too much work for me to maintain multiple versions and address bug reports from all different versions.

Is there a reason you want to downgrade? If you're experiencing any issues with the latest version, I'd be happy to address them.

**Comment by canplx** [comment]
no that's alright I just wanted to see If other versions were available thanks though.
