### ISSUE TITLE
Mod confirmed to work with old version 1.4.10,  1.5.5 is not working

### ISSUE THREAD

**Issue by kaioken32** [Kizari/Flagrum#124]
Luckily I had old flagrum version 1.4.10
and I have all the mods suddenly worked 

clearly the issue lies with the latest version
kindly look into it

**Comment by Kizari** [comment]
You already have an open issue on this matter.
Kindly refrain from posting duplicate issues.

**Comment by Vaan749** [comment]
I have the same problem like you
Kaioken32 can you send me the old version of flagrum

**Comment by Kizari** [comment]
The old versions of Flagrum were intentionally removed from the releases page on this repository because it's not safe to migrate backwards (it can corrupt all of your mod data) and they're not compatible with newer mods anyway. If you're having a problem with the latest Flagrum release, please open a new issue with as much detail as possible so we can work together to try and address it.
