### ISSUE TITLE
Flagrum gets stuck on "Indexing game files" for hours

### ISSUE THREAD

**Issue by pcthekid** [Kizari/Flagrum#39]
Stuck at indexing files. Stays there for hours.

**Comment by Kizari** [comment]
There are two known things that can cause this.

1. If you don't have FFXV installed or have set your EXE path wrong in the settings, it will never be able to finish indexing. I would suggest making absolutely sure your EXE path is set correctly then restarting Flagrum if it was changed.

2. Older or slower hardware, particularly 5400rpm HDDs can take much longer to index than modern hardware. For me personally, the index process takes ~2 minutes, but one user on an old laptop reported theirs took an hour and a half. The only solution if this is your problem is to leave it running for longer. Although if it has already been more than 2 hours, then I have a feeling this is not your issue.

You could also try switch tabs on the left menu in case the UI hasn't updated after the indexing finished. If the message goes away when you switch tab, then you're good to go.

Let me know how you get on, and if you have any more information you could possibly provide, please do so.

**Comment by pcthekid** [comment]
Thank you so much for the reply. I have a relatively strong and fast gaming
PC, so I don't think that's the issue. The exe file is located on an
external hard drive and I wonder if that could be the issue. Have you come
across anything like that before? I wonder too, if that's the case, would
it make a difference if I moved to the exe file to a folder that's on my PC
and not on the hard drive.

Harold O'Neal FRSA
Pianist • Producer • Speaker • Social Entrepreneur

**Comment by pcthekid** [comment]
I'll also give letting it index overnight a shot. Thanks again!

Harold O'Neal FRSA
Pianist • Producer • Speaker • Social Entrepreneur

**Comment by Kizari** [comment]
Let me know how it goes.

I have heard of at least one other person having issues with the game being on an external HDD. They resolved it by moving it onto their main SSD. A little odd though, I'd expect it to be fine, just take a little longer.

**Comment by Kizari** [comment]
A Discord user just reported that they were having the same problem. They were able to fix it by going to the "Settings" tab on the left menu, and clicking "Regenerate File Index." After doing this, it finished indexing within 5 minutes. They were using an SSD for both Flagrum and the game though, so the time may vary. Might be worth a try if you're still not having any luck.

**Comment by pcthekid** [comment]
Thank you! Sounds promising. I'll give this a try when I get home.

Harold O'Neal FRSA
Pianist • Producer • Speaker • Social Entrepreneur

**Comment by pcthekid** [comment]
Regenerating the file index worked for me. I'm all set! Thanks for the help.

Harold O'Neal FRSA
Pianist • Producer • Speaker • Social Entrepreneur

**Comment by Kizari** [comment]
Glad to hear it. Thanks for letting me know. Not sure what would cause this, but at least there's a workaround until it can be solved.

**Comment by Kizari** [comment]
I think I may know what causes this. The code that triggers the file indexing runs when the application first loads up, but if the paths aren't set, it can't do so. Upon setting the path, it then transitions to the main UI. The main UI claims to be indexing based on a state value, but it actually isn't indexing at all. The solution therefore would be to trigger the indexing code to run upon setting the game path if the index isn't already populated.

Funnily enough, this came to light while developing Flagrum 1.4's new "profiles" system. When changing to a new profile, I ran into this because I don't have Forspoken installed in the usual location, so it couldn't autodetect. Upon setting the path, I ran into this exact issue. I was able to solve it by closing Flagrum, relaunching it (the path is now set), and waiting ~2 minutes for indexing to complete. Of course, the "Regenerate File Index" button in the settings tab would also achieve the same result.

I will ensure this issue is resolved in Flagrum 1.4.0.

**Comment by pcthekid** [comment]
Thank you for the update. This makes sense to me, though I do not know a
lot about creating these types of applications.

Harold O'Neal FRSA
Pianist • Producer • Speaker • Social Entrepreneur

**Comment by Kizari** [comment]
This issue has been fixed as of Flagrum 1.4.0.

**Comment by pcthekid** [comment]
Cool! Thank you for all of your work and effort!

Harold O'Neal FRSA
Pianist • Producer • Speaker • Social Entrepreneur
