### ISSUE TITLE
Enabled mod but didn’t gets detected as enabled, and I can't enable it from flagrum again (it is still enabled in the game just fine) 

### ISSUE THREAD

**Issue by orangpelupa** [Kizari/Flagrum#4]
The mod is the one for removing colissions

https://www.nexusmods.com/finalfantasy15/mods/220

**Comment by Kizari** [comment]
Thanks for you report.

What exactly is happening when you attempt to enable the mod?

If the application is crashing, please share the contents of your `crash.txt` file located at:
```
%localappdata%\Flagrum\crash.txt
```

If something else is happening, please describe what to the best of your ability including any error messages that appear (if any).

**Comment by orangpelupa** [comment]
hello. here it is 
[crash.txt](https://github.com/Kizari/Flagrum/files/9462104/crash.txt)

**Comment by Kizari** [comment]
Perfect, thank you!

Flagrum appears to be unable to backup the original files that this mod alters due to them being missing from the original earc. Had you manually installed any mods from Nexus or anywhere else prior to installing Flagrum? If so, that can cause such issues.

If this is the case, this section of the Wiki explains how to properly set your game up for use with the Mod Manager to ensure such issues don't occur.
https://github.com/Kizari/Flagrum/wiki/Using-the-Mod-Manager#important-preparation

**Comment by orangpelupa** [comment]
I didn't install mods before flagrum. I did use cheat engine.

The issue with flagrum begins with (I should have included this in the first place, sorry!) 

1. Install flagrum,
2. Install the colissions mod
3. Reboot computer
4. Instead of running flagrum from start menu, install flagrum again
5. Collision mod missing from flagrum. Install colissions mod again
6. Flagrum crash
7.

Anyway, flagrum still works fine for other mods, so I'm too lazy to reinstall / cleanup the game files.

**Comment by Kizari** [comment]
Ahh yes, this makes sense. Because you reinstalled Flagrum after installing the collisions mod, the collisions mod was still applied to the game but you accidentally wiped the data Flagrum uses to track which mods are currently applied. I can't promise this won't cause you any more issues in future if other mods target similar files, but if things start to fail unexpectedly, you can always cleanup the game files in future and reinstall your desired mods.

**Comment by orangpelupa** [comment]
No worries! Sorry for my weird use case. Btw Maybe put this in low priority work? 

flagrum should show a pop up/error message saying "the files has been modified, and flagrum have no record of it, please consider repairing/reinstall the game"

So weird people like me won't just get flagrum crashing with no info.

**Comment by Kizari** [comment]
As requested, unhandled exceptions while enabling/disabling mods that don't otherwise have a known cause should be caught and prompt the user to take appropriate action rather than simply crashing.

- A popup should explain this problem to the user
- A link to the relevant documentation should be present and correspond to the active localisation
- The developer needs to consider that the game files may not be the only issue—Flagrum may also be in a bad state. The documentation should instruct the user on how to handle these cases also. If possible, this should also be reflected in the popup warning in-app also

**Comment by Kizari** [comment]
Unfortunately time did not permit getting this fix into 1.2.5, so it will be pushed back to the next maintenance update.

**Comment by Kizari** [comment]
This has been addressed with Flagrum 1.3.
