### ISSUE TITLE
Issues in Model Replacement tab

### ISSUE THREAD

**Issue by SevenShanks** [Kizari/Flagrum#41]
The following issues apply to the Model Replacement tab in Workshop Mods > New Mod > Type: Model Replacement.

- When editing an already-saved custom Model Replacement preset, I cannot save it with an unchanged name because the program thinks it is "already in use by another preset".
- I cannot use the asset browser when creating or editing custom Model Replacement presets, because it thinks a file indexing is going on. This is not true.

**Comment by Kizari** [comment]
I am able to reproduce both of these issues fine.

The first issue can be worked around until it's fixed by choosing a different name. It can then be changed back to what it was originally and saved again.

I tried to workaround the asset browser issue by manually entering the path, but that caused the following error when trying to save:

> The property 'ModelReplacementPath.Path' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal.

It seems there is no workaround for this currently, unfortunately. I will get these both fixed in the next update.

**Comment by Kizari** [comment]
These issues have both been fixed as of Flagrum 1.4.0.
