### ISSUE TITLE
Mod Corruption (Possibly two different bugs)

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#57]
1) Larger mods such as Wizmas and Mogfest become corrupted after a few rebuilds. 
An earc was reported missing. No other log info currently

2) Flagrum will occasionally mark some or every mod as corrupted, however restarting flagrum or possibly even just tabbing out and back in will be enough for Flagrum to no longer think there is an issue.

**Comment by Kizari** [comment]
An attempt has been made to fix this issue in Flagrum 1.4.7. The problem is, I'm unsure why it happens in the 1.4.6 release, but not earlier debug builds or the 1.4.7 release build. Perhaps it was caused by a bad build cache (bin/obj), or perhaps some changes in 1.4.7 has resolved the problem. Will keep an eye on the issue to make sure it doesn't regress.
