### ISSUE TITLE
Older Binmod Metadata for Replacements causes failure to load

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#59]
Three mods, two of which had been made then uploaded to steam via Flagrum, and another which remains local only both have started causing Flagrum to crash when selected via flagrum, however remain fine when accessed via the in game mod manager. These binmods all behaved normally at creation and have had no issues in game or on steam, and the *.binmod files have been unaltered since their original creation date. 

First noticed by log.txt mentioning it failed to read metadata from a single binmod. Which caused me to click on each mod to find the matching one, resulting to discover three caused flagrum to crash. I have tried deleting the binmod.list, and having it regenerate with game boot. The log.txt no longer reports the issue, but Flagrum still crashes when accessing those mods. 

Console crash:
```
blazor.webview.js:1  Value cannot be null. (Parameter 'name')
   at Microsoft.Extensions.Localization.StringLocalizer`1.get_Item(String name)
   at Flagrum.Web.Features.WorkshopMods.Editor.Index.<BuildRenderTree>b__127_2(RenderTreeBuilder __builder3) in C:\Code\Flagrum-Patreon\Flagrum.Web\Features\WorkshopMods\Editor\Index.razor:line 117
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Flagrum.Web.Components.Layout.LoadingView.BuildRenderTree(RenderTreeBuilder __builder) in C:\Code\Flagrum-Patreon\Flagrum.Web\Components\Layout\LoadingView.razor:line 8
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
NotifyUnhandledException @ blazor.webview.js:1
```

Flagrum's full [crashlog:](https://github.com/Kizari/Flagrum/files/11240877/crash.txt)

Image of meta data within binmod
![image](https://user-images.githubusercontent.com/108095289/232258157-34ecedc2-36ef-4205-a707-db4d20e70acd.png)

![image](https://user-images.githubusercontent.com/108095289/232258464-4eb9233e-f0cd-4913-a47f-1f88b5849f4f.png)
![image](https://user-images.githubusercontent.com/108095289/232258475-f3918a81-0ccd-41d8-9c0b-eebe47e4c9ef.png)
![image](https://user-images.githubusercontent.com/108095289/232258484-4fa6862c-31cc-448d-8863-4b2882c9613d.png)

All three of these mods were made using the custom model replacement option that was updated at some point. I believe this change may have caused the error. My most recent custom model replacement for Choco-Girl in Wizmas does not have this issue, and believe it was made with the custom presets *after* the update.

Developer should consider ignoring this thread as its very likely I'm the only one to have ever used this system prior to the update or even since. 

Users experiencing this error should remake the mod with the updated flagrum custom templates to prevent this issue.

**Comment by Kizari** [comment]
This has to do with an oversight on the development of the model replacement system. The custom presets are stored in one's local data, but if that data is cleared at any point (such as during a reinstall), or the custom model replacement binmod has come from someone else (such as via Steam Workshop), Flagrum doesn't have the name of the preset in the user data (or has the wrong name associated with the same ID). Since the binmod system is so broken due to SE's mismanagement and early cancellation of the mod functionality, I'm not going to invest the time to fix this one—especially since the binmod system will likely be made redundant in future. Instead, I'll simply avoid the null issue so at least this page will load correctly for affected mods.

This issue has been resolved in Flagrum 1.4.7.
