### ISSUE TITLE
MOD Changes not being reflected with build updates

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#63]
This bug presents itself when using the pencil icon to change targets for build instruction sources. 

Under certain conditions, Flagrum either fails to detect the change in files, possibly due to similar timestamps or possibly due to an error with the clear cache function. However, disabling and enabling correctly applies the change as intended. 

To Replicate:
1) Batch export via flagrum on `data://effects/environment/common/entity/envfx_fireworks/vfx/`
2) Replace a file (i was just using one of those vfx and using a different one as a test)
3) After saving, go back in and retarget the change with a different VFX
4) Check which vfx is applied (i was using file size as clear indicators)
5) Attempt to clear cache and resave
6) Disable the mod fully and resave
7) Delete the instruction to revert successfully

Check which vfx is applied to the game within Asset Explorer between each step

![image](https://user-images.githubusercontent.com/108095289/233199889-8147893d-d9de-44d5-8119-deefd17b9ff2.png)

![image](https://user-images.githubusercontent.com/108095289/233199860-e80f4adc-695c-4112-803e-de14e0a440b8.png)

Legend: 
i swapped moning.vfx with light.vfx for v1 
changed target to once.vfx for v2
cleared cache then saved for v3
then disabled and enabled and got v4
deleted the instruction and got v5

Developer should verify cache clearing function to ascertain the differences between disabling's usage of the function, vs the buttons usage of the function. As well as confirm the function is getting called if timestamps are nearly identical when selecting a new target for an instruction. 

Users are encouraged to disable a mod fully and enable it till an update addresses this issue, however will not be needed if the changes to the mod are new instructions being added.

**Comment by Rinual** [comment]
after using the clear cache button and then saving, re entering the mod does not return the ability to clear the cache again until you disable and re-enable the mod. 
possibly related

**Comment by Kizari** [comment]
An issue was identified where using the pencil icon to change a replacement path could sometimes cause the error outlined above due to the timestamp of the file being identical. Flagrum would not rebuild the cache file because the timestamp was suggesting the file hadn't been altered (cached files are tracked by URI, not file path).

A fix has been applied to the `UpdateReplacementPath` method that sets the timestamp back to 0 so that it will be detected as modified, and the issue appears to be sorted now in Flagrum 1.4.9.

This issue should be reopened if other conditions are found under which the problem can occur.
