### ISSUE TITLE
Flagrum erroneously reports MOD corruption 

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#64]
At times flagrum has prompted me about a mod being corrupt. Recommending i force disable and validate my files. However, this error stops being presented shortly after. 

In one instance, flagrum told me every mod i had was corrupted, but reopening flagrum all mods were fine. 

Other instances, it will tell me a mod, even a single instruction replacement mod is corrupt, however the warning is bypassed by attempting to disable the mod a third time. 

I have verified with that single replacement that the backup is being properly restored, and the mod is applying the changes as intended, so no issue warrants needing to validate, nor does it explain what would cause flagrum to think its corrupted then change its mind. 

This is currently flagged as low priority as the bug is infrequent, and the workaround will suffice and allow mods to continue to be built. 

If anyone finds a reliable way to trigger this, please comment below, currently however it is a bit ambiguous.

Users who experience a mod corruption warning are encouraged to try closing and reopening flagrum or disabling the mod multiple times via the checkmark before resorting to validating their files. However validating their files will still ultimately work as well, and helps ensure no other issues are interfering.

**Comment by Kizari** [comment]
This seems to be related to #60. The corruption popup displays if any exception occurs during the build process, because historically the only thing that has caused this is when a file was corrupted. For now I will leave this behaviour as it is, since fixing #60 will return this to being the reality of the situation. However, it may not be a terrible idea to consider what constitutes file corruption, and to specifically catch only relevant exceptions before displaying that popup. Some of the errors that can occur are quite generic though, so this would be a rather large undertaking. For now, I don't think it's worth the time, so I won't open a new issue about it.

Closing this as I'm hoping the solution to #60 will resolve it. If it persists, this issue should be reopened.
