### ISSUE TITLE
Critical Bug: Steam Workshop upload hangs indefinitely

### ISSUE THREAD

**Issue by NightysWolf** [Kizari/Flagrum#77]
It seems that under Flagrum 1.4.1 it's not possible to upload binmods to Steam. Flagrum shows an infinite uploading screen without progress and needs to be terminated manually.

**Comment by Kizari** [comment]
It would seem this is most likely related to the switch from manually copying the Steamworks DLLs to using the Steamworks NuGet package. Theoretically these two things should be no different in practice, but we all know what computers are like. Best course of action will probably be to go back to the manual approach since I really cannot be bothered trying to fight Steam's horrible API with the more convenient method in the hopes of maybe figuring out a solution. Better to just grab the low hanging fruit sometimes.

**Comment by Kizari** [comment]
This has been reverted to the old behaviour in Flagrum 1.4.11.
