### ISSUE TITLE
Flagrum not installing FOMDS stating File is in Use

### ISSUE THREAD

**Issue by ZombieMonkeyNZ** [Kizari/Flagrum#86]
When trying to install The Moogle Chocobo Carnival and Expanded Area VFX mods Flagrum throws and error stating that the files are in use.

No other process is accessing the files and I have downloaded new copies of the files. Crash log: https://pastebin.com/DnVezJPe

Several other mods have installed correctly prior to attempting to install these two mods.

**Comment by Kizari** [comment]
I'm afraid I'm not sure what could cause the files to be locked if nothing else on your system is doing so. Thank you for the crash log. Unfortunately it doesn't provide much extra context in this case, so will need to ask some extra questions.

1. You mentioned the issue was happening when *installing* the mods. Are the mods sitting in the "Inactive Mods" tab inside Flagrum now, or did the mod cards not get added at all? If they are there, are you able to enable them via the right-click option?

2. Either very rarely, or due to software bugs, files can become "stuck" in a locked state. Have you tried again after restarting your PC since this issue first occurred?

**Comment by ZombieMonkeyNZ** [comment]
Flagrum would crash when attempting to install however, the mods would show up in the Disable Mods tab. Attempting to active the mod would get Flagrum stuck.

I've done a complete reinstall of FF15 and Flagrum and the mods have installed correctly, so unsure if it was related to Flagrum itself or something else.
