### ISSUE TITLE
Preview of enabled mod functionality lost in Flagrum V1.5 - enhancement request

### ISSUE THREAD

**Issue by MrsFlowerpot** [Kizari/Flagrum#96]
As a consequence of the v1.5 update Flagrum's asset explorer no longer displays the modified texture files of enabled mods and the model preview no longer displays the modified textures of enabled mods. 

I appreciate the improvements in Flagrum but I miss this functionality.  Is there any way to emulate these features and put them back in Flagrum?  It was especially useful and convenient to be able to preview models with the enabled mod applied.

**Comment by Rinual** [comment]
Subject: Preview of enabled mod functionality lost in Flagrum V1.5

Hi Mrsflowerpot,

Thank you for using Flagrum and providing feedback on the recent v1.5 update. The changes made affect how asset previews function, particularly with modified textures and model previews.

Due to our current system architecture and the nature of our patching mechanism, replicating the previous preview functionality directly isn't feasible. The staging area and compressed data handling present challenges for real-time previews.

It's worth noting that unpacking the game files and utilizing Blender can address many of the features you've mentioned. Blender provides a platform for viewing models and offers live previews of texture changes. While we can't emulate the exact previous functionality, we encourage you to continue using Flagrum for its intended purpose. If you encounter technical challenges or have specific use cases, feel free to share, and we'll do our best to assist within the existing system framework.

Thank you for your understanding and ongoing support.

Best regards,

Rinual
